image: python:3.12-bullseye
pre-commit:
  only: [main, external_pull_requests]
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
    - ${PIP_CACHE_DIR}
    - ${PRE_COMMIT_HOME}
  script:
  - pip install pre-commit
  - pre-commit run --all-files
