build: false
branches:
  only: [main]
cache:
- '%LOCALAPPDATA%\pip\cache'
- '%USERPROFILE%\.cache\pre-commit'
install:
- SET PATH=C:\Python312;C:\Python312\Scripts;%PATH%
- pip install pre-commit
test_script: pre-commit run --all-files
